### ISSUE TITLE
No implicit support for Long

### ISSUE THREAD

**Issue by idctim** [zamblauskas/scala-csv-parser#20]
When trying to convert .csv data from a stream or file that has made it to a comma and new line delimited string into a case class used by an application, it would be good (in certain circumstances, essential) to have an expanded list of "native" Scala types. Presently, there is support for the following types:

String
Int
Float
Double
Boolean

I propose adding Long to this list and have created a Pull Request for this. 

Why is this essential? When dealing with AWS S3 Objects, the document info needed to fully describe an entry includes a Long type for the content-length. The other types that might be considered important to support are BigDecimal and BigInt, but they are more involved since they do not have implicit converters in Scala's StringOps class. BigDecimal is used for money a lot in many projects including Squants, and it is also used extensively in default situations for Slick and Postgres. Big Int could come along for the ride. I will work on a Pull Request for the Bigs, but Long is terribly time sensitive, so if the Long pull request could be approved very soon, that would be most appreciated!

**Comment by zamblauskas** [comment]
Hi, thanks so much for your PR,
it's merged and deployed on 0.11.5

**Comment by idctim** [comment]
Hi!

Thanks so much. I took an initial pass at adding it to the project (which is already in production by the way), but failed to integrate it. I will make another report in a week: successes and failures. 

Thank you for all your hard work!!!
Tim Moore
