### ISSUE TITLE
Bintray no longer available

### ISSUE THREAD

**Issue by luis3m** [zamblauskas/scala-csv-parser#22]
@zamblauskas Hi, with Bintray down permanently there's no artifact available to use this library.

**Comment by zamblauskas** [comment]
Hi,

It's now available on [Maven Central](https://mvnrepository.com/artifact/io.github.zamblauskas/scala-csv-parser)
```
"io.github.zamblauskas" %% "scala-csv-parser" % "0.13.1"
```
